name: Demo Workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello, world!"

      - name: 22f2001391@ds.study.iitm.ac.in
        run: echo "Email verified"
